name: Deploy personal website to S3 bucket

on:
  push:
    branches:
      - main
    paths:
      - "index.html"
      - "styles.css"
      - "assets/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync website to S3
        run: aws s3 sync . s3://$S3_BUCKET_NAME --exclude ".git/*" --exclude ".github/*" --exclude "README.md" --delete

        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
